title: HOWTOBECOMEACRAB.COM
description: demiurgic messaging systems and chitin delivery
baseurl: "/howtobecomeacrab"
url: "https://blhls.github.io"

theme: minima
permalink: /:year/:month/:day/:title/
